"""empty message

Revision ID: 55d63012bb4e
Revises: 713841677f59
Create Date: 2017-09-26 03:44:23.560755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d63012bb4e'
down_revision = '713841677f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_picture', sa.Column('url', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_picture', 'url')
    # ### end Alembic commands ###
