"""empty message

Revision ID: 713841677f59
Revises: a86e0d8d0fb6
Create Date: 2017-09-26 00:39:45.111849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713841677f59'
down_revision = 'a86e0d8d0fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_picture', sa.Column('upload_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_picture', 'upload_date')
    # ### end Alembic commands ###
