"""empty message

Revision ID: a86e0d8d0fb6
Revises: f6fec4b4d1e5
Create Date: 2017-09-25 18:32:12.796647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a86e0d8d0fb6'
down_revision = 'f6fec4b4d1e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_picture', sa.Column('content_length', sa.BigInteger(), nullable=True))
    op.add_column('upload_picture', sa.Column('content_type', sa.String(length=50), nullable=True))
    op.add_column('upload_picture', sa.Column('filename', sa.String(length=100), nullable=False))
    op.add_column('upload_picture', sa.Column('path', sa.String(length=100), nullable=False))
    op.drop_column('upload_picture', 'file')
    op.drop_column('upload_picture', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_picture', sa.Column('slug', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('upload_picture', sa.Column('file', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('upload_picture', 'path')
    op.drop_column('upload_picture', 'filename')
    op.drop_column('upload_picture', 'content_type')
    op.drop_column('upload_picture', 'content_length')
    # ### end Alembic commands ###
